### PR TITLE
Test using Jasmine for more effective testing

### PR DESCRIPTION
**Pull request by hiromu2000**
Hi James,

I forked your project and started developing a new one with a slightly different concept.
During my development, I wrote a test using Jasmine, which I think would be beneficial for your project.
I added a spec only for test1.html and test8.html, but I am ready for writing other specs when you would accept my pull request. 
Please open the SpecRunner.html in your preferred browser and see how the test works.
I would appreciate any feedback, question, and request.

Thanks,
Hiromu

### CODE REVIEW

**Comment by jamesandres** [comment]
Hi Hiromu, your fork looks like a great idea! Best of luck to you.

Thanks for the Jasmine tests. I'll have a look tomorrow.

**Comment by jamesandres** [comment]
Looks good overall. I'm going to tweak a few things before committing. Thanks again!

**Comment by hiromu2000** [comment]
Thanks for reviewing.
You might want to change the tests/spec/spec.js 
from "DOM Parser check for " to something else since it is not a DOM parser, which I realized after I made a pull request.

**Comment by jamesandres** [comment]
I've added more test for the remaining files and shuffled a few things around. Some of the actual tests could be improved. Will take a look at that later.

**Pull request merged**
